<form action="/index/index" method="post" id="change-password" novalidate="novalidate">
    <div class="form-item">
        <label for="password">Password</label>
        <?= $this->element->password ?>
    </div>
    <div class="form-item">
        <label for="password2">Confirm Password</label>
        <?= $this->element->password2 ?>
    </div>
    <div class="form-item">
        <input type="submit" class="submit" value="Update Password">
    </div>
</form>