
<h1>Welcome to Office Builder<?= $this->user ? ', '.ucfirst(strtolower($this->user->getFirstName())) : '' ?></h1>

<h2>Check out our Products</h2>
<ul>
    <?php foreach (OfficeBuilder_Model_Product::getCategories() as $categoryIndex => $categoryName) : ?>
        <li><a href="/products/index/category/<?= $categoryIndex ?>"><?= $categoryName ?></a></li>
    <?php endforeach; ?>
</ul>

<?php if (!$this->user): ?>

    <h2>Already have an account?</h2>
    <ul>
        <li><a href="/auth/login">Login</a></li>
    </ul>

    <h2>Need to create an account?</h2>
    <ul>
        <li><a href="/users/signup">Sign Up for OfficeBuilder</a></li>
    </ul>

<?php else: ?>

    <h2 style="margin-top: 26px;">My Profile</h2>

    <div id="tabs" style="padding-top: 10px;margin-top: 0px;">
        <div class="" style="border-left:none; padding-top: 0px;margin-top: 0px;">
            <div class="panel" id="account-overview" style="display: block; width: 900px;">
                <div class="panel-content">
                    <div class="col-2 col row account-info">
                        <div class="block-1 block user-info">
                            <header>
                                <span class="title">Account Info</span>
                            </header>
                            <div class="info">
                                <div class="alert-message green" id="color-update">
                                    <span>Favorite color successfully updated.</span>
                                </div>
                                <div class="alert-message red">
                                    <span></span>
                                </div>
                                <div class="name">
                                    <span><?= $this->user->getFirstName() ?></span>
                                    <span><?= $this->user->getLastName() ?></span>
                                </div>
                                <div class="email">
                                    <span><?= $this->user->getEmail() ?></span>
                                </div>
                                <div class="email">
                                    <span><?= $this->user->isAdmin() ? 'Admin User' : 'Basic User' ?></span>
                                </div>
                            </div>
                            <header>
                                <span class="title"></span>
                            </header>
                            <div class="info">
                                <div class="address">
                                    <span>Favorite Color</span>
                                    <select id="fav-color" data="<?= $this->user->getId() ?>">
                                        <?php
                                        foreach (OfficeBuilder_Model_User::getColorOptions() as $currColor)
                                        {
                                            echo '<option value="'.$currColor.'"'.($currColor == $this->user->getFavoriteColor() ? ' selected' : '').'>'.$currColor.'</option>';
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="block-2 block change-password">
                            <header>
                                <span class="title">Change Password</span>
                            </header>
                            <div class="alert-message green"<?= $this->passwordMsg ? ' style="display:block;"' : '' ?>>
                                <span><?= $this->passwordMsg ?></span>
                            </div>
                            <div class="alert-message red"<?= $this->passwordError ? ' style="display:block;"' : '' ?>>
                                <span><?= $this->passwordError ?></span>
                            </div>
                            <?= $this->passwordForm ?>
                        </div>
                    </div>
                    <div class="payment-info">
                        <header>
                            <span class="title">Purchase History</span>
                        </header>
                        <div class="cards">
                            <table width="100%">
                                <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Product</th>
                                    <th>Spots</th>
                                    <th>Price</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                    if ($this->purchases)
                                    {
                                        /* @var OfficeBuilder_Model_Purchase $currPurchase */
                                        foreach ($this->purchases as $currPurchase): ?>
                                            <tr>
                                                <td><?= date('n/j/Y g:i a', strtotime($currPurchase->getCreatedOn())) ?></td>
                                                <td><?= $currPurchase->getInventory()->getProduct()->getName().' ('.$currPurchase->getInventory()->getPeriodDescription().')' ?></td>
                                                <td><?= number_format($currPurchase->getUnits()) ?></td>
                                                <td>$<?= number_format($currPurchase->getPpu(), 2) ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                <?php } else { ?>
                                    <tr><td colspan="5"><br>No purchases. Please browse our services above!</td></tr>
                                <?php }  ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>